export const demoNews = [
  { id: 'demo-nvda', source: 'Port. Beispiel', category: 'Unternehmen', minutes: 4, symbols: ['NVDA'], title: 'KI bleibt der große Treiber. Was das für NVIDIA bedeutet.', summary: 'Ein Beispiel für deinen persönlichen Newsfeed: Entwicklungen rund um KI-Infrastruktur werden deiner NVIDIA-Position zugeordnet.', body: 'Diese Nachricht ist ein Designbeispiel und kein aktueller Marktbericht. Im Live-Modus werden tatsächlich veröffentlichte Meldungen mit Quelle und Veröffentlichungszeit abgerufen. Die Relevanz richtet sich nach den betroffenen Positionen und ihrem Anteil an deinem Portfolio.', tone: 'Im Fokus', image: 'chip', featured: true },
  { id: 'demo-apple', source: 'Port. Beispiel', category: 'Unternehmen', minutes: 12, symbols: ['AAPL'], title: 'Der nächste Produktzyklus rückt in den Fokus.', summary: 'Produkte, Nachfrage und Lieferketten: die Themen hinter deiner Apple-Position.', body: 'Beispielmeldung zur Apple-Position. Ein Produktzyklus kann für die Nachfrage und die Umsatzentwicklung relevant sein. Dies ist keine echte Nachricht und keine Kursprognose.', tone: 'Produktupdate', image: 'apple' },
  { id: 'demo-fed', source: 'Port. Beispiel', category: 'Makro', minutes: 23, symbols: ['NVDA', 'AAPL', 'MSFT', 'TSLA', 'AMZN'], title: 'Zinsen bewegen Märkte. Dein Portfolio hört mit.', summary: 'Makroökonomische Meldungen werden mit dem gesamten Portfolio verknüpft.', body: 'Beispielmeldung zur Zinspolitik. Zinsentscheidungen können mehrere Positionen gleichzeitig betreffen. Im Live-Feed stammen Meldungen aus dem Google-News-RSS-Index; für Makromeldungen erfolgt eine portfolioübergreifende Zuordnung.', tone: 'Marktumfeld', image: 'macro' },
  { id: 'demo-msft', source: 'Port. Beispiel', category: 'Unternehmen', minutes: 36, symbols: ['MSFT'], title: 'Cloud und KI: zwei Wachstumstreiber, ein Blick aufs Ganze.', summary: 'Die Entwicklungen, die deine Microsoft-Position betreffen, an einem Ort.', body: 'Beispielmeldung zur Microsoft-Position. Das Dashboard bündelt Informationen, ohne daraus eine Kauf- oder Verkaufsempfehlung abzuleiten.', tone: 'Im Fokus', image: 'cloud' },
  { id: 'demo-tesla', source: 'Port. Beispiel', category: 'Unternehmen', minutes: 48, symbols: ['TSLA'], title: 'Neue Auslieferungszahlen. Neue Fragen für Tesla.', summary: 'Operative Updates geben den Bewegungen im Portfolio Kontext.', body: 'Dies ist ein fiktives Beispiel zur Darstellung einer operativen Unternehmensmeldung. Es werden keine tatsächlichen Auslieferungszahlen behauptet.', tone: 'Operatives Update', image: 'tesla' },
  { id: 'demo-amzn', source: 'Port. Beispiel', category: 'Quartalszahlen', minutes: 65, symbols: ['AMZN'], title: 'Der Blick hinter die Zahlen: Amazon im Quartalscheck.', summary: 'Ergebnisse, Margen und Ausblick werden deinem Portfolio zugeordnet.', body: 'Fiktive Meldung zur Darstellung einer Quartalsnachricht. Echte Nachrichten werden mit einer externen Quelle verlinkt. Port. berechnet keine Handelsentscheidungen.', tone: 'Ergebnisse', image: 'amazon' },
];
export const brokers = [
  { name: 'Trade Republic', mark: 'tr', color: '#202624' },
  { name: 'Robinhood', mark: '↗', color: '#c8eb65' },
  { name: 'Revolut', mark: 'R', color: '#202624' },
  { name: 'Fomo', mark: 'f', color: '#d2c3f0' },
  { name: 'Andere Quelle', mark: '+', color: '#e9ebe6' },
];
